### ISSUE TITLE
Add d-portal SSH keys

### ISSUE THREAD

**Issue by hayfield** [IATI/deployment#5]
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiD5YKdszmWOFDHco51vmpDOy+VjXaMQKIwSi7TCCCTFvy5dwqM0DwbHZZEgFHohT1jDqlm2adHeiHn27yv+VKfP9sGFWM7/tPGKpCTt01S/IDwmsFS/ZhgK6KI9W/YntS3QbuHkCso2rNOLDq2fxvlpOXXOMw/qDULGIKTOf+SMxmvjX4KgCQ271dE7L+OGR2wXB8l4G1bzaSFLTAXnxc0ulJATXYYOAAsY2qWhTax5tNG0K2zItiOZWffwmVKw4QwLutTCKW2qqJb8cKgawRWL48FR8cV04A8eShXF/7k9pJfKNMCMRtA1zeRGGC/zTXgyelRrSpzduy/y4ZpBEl notshi@gmail.com

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdx+ZGNaTFfqwUzphFSP7m03bu0kLYDuvVg/BXqtimIEPfYTv6K4mZPz7gpsV9OChOX70Y0KHbWVegr6pNUN0h6YxCcOlCRq5/ylifDM08K3SCd/R13MJVvbDuXiBzGflEW2WBPy1zyMEI2SR9lv5PfsRquZnjfDlejn/sLzaZ/PUVHpuweOfGdpKseCM3kh7XhwDAPwGxBx0ckafeiPZjtK0T+yiKR3SXysa2FB5UzW1WBKBqupZXrjgeQ8RC1MKK3MQAPyfiYWT57wsQqyOyPA0oVRKsoez+I3uRWp4KZm9DRya5v231Hw8YuCPWMdPrPUjkafP+RImvBHmEdC1T kriss@xixs.com
```

**Comment by samuele-mattiuzzo** [comment]
Hello @hayfield , is this issue still relevant? Do we need further actioning on it? If so, do you still have context/memory around this?

**Comment by hayfield** [comment]
There's ansible setup to add SSH keys to servers - https://github.com/IATI/deployment/tree/master/roles/configure_ssh_keys. At one point the list of servers included the d-portal server. Running the "set SSH keys" task then overwrote Kriss and Shi's SSH public keys.

The interim solution was to not mange the d-portal server as part of this repo - https://github.com/IATI/deployment/blob/master/servers.ini#L24. An alternative solution would be to include Kriss and Shi's keys as part of the list of permitted keys for the d-portal server. The public keys noted in this Issue are those keys.

**Comment by samuele-mattiuzzo** [comment]
Thank you! Will discuss this with the team, but I think we'll opt for an update on the ansible script with those two keys. Will keep you up to date on this
